version: '3.8'

services:
  grpc_server:
    build:
      dockerfile: Dockerfile
    container_name: grpc_server
    ports:
      - "50051:50051"
    networks:
      - coachcraft_network

networks:
  coachcraft_network:
    external: true
