version: '3.8'

services:
  grpc_server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: grpc_server
    networks:
      - my_network
    ports:
      - "50051:50051"


networks:
  my_network:
    driver: bridge