version: '3.8'

services:
  PFScraperAPI:
    build:
      dockerfile: Dockerfile
    container_name: PFScraperAPI
    ports:
      - "8001:8001"
    networks:
      - coachcraft_network

networks:
  coachcraft_network:
    external: true
