# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
# Make port 50051 available to the world outside this container
EXPOSE 50051

# Run server.py when the container launches
CMD ["python", "scraper/core/scraper_server.py"]