version: '3.8'

services:
  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_server
    ports:
      - "50051:50051"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
