# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scraper.core import scraper_pb2 as scraper_dot_core_dot_scraper__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scraper/core/scraper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScraperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNinetyZPNs = channel.unary_unary(
                '/scraper.ScraperService/GetNinetyZPNs',
                request_serializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
                response_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
                _registered_method=True)
        self.GetNinetyLeagues = channel.unary_unary(
                '/scraper.ScraperService/GetNinetyLeagues',
                request_serializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
                response_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
                _registered_method=True)
        self.GetNinetyLeagueStandings = channel.unary_unary(
                '/scraper.ScraperService/GetNinetyLeagueStandings',
                request_serializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
                response_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
                _registered_method=True)
        self.GetNinetyFixtures = channel.unary_unary(
                '/scraper.ScraperService/GetNinetyFixtures',
                request_serializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
                response_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
                _registered_method=True)
        self.GetNinetyTeams = channel.unary_unary(
                '/scraper.ScraperService/GetNinetyTeams',
                request_serializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
                response_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
                _registered_method=True)


class ScraperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNinetyZPNs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNinetyLeagues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNinetyLeagueStandings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNinetyFixtures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNinetyTeams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScraperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNinetyZPNs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNinetyZPNs,
                    request_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.FromString,
                    response_serializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.SerializeToString,
            ),
            'GetNinetyLeagues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNinetyLeagues,
                    request_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.FromString,
                    response_serializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.SerializeToString,
            ),
            'GetNinetyLeagueStandings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNinetyLeagueStandings,
                    request_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.FromString,
                    response_serializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.SerializeToString,
            ),
            'GetNinetyFixtures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNinetyFixtures,
                    request_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.FromString,
                    response_serializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.SerializeToString,
            ),
            'GetNinetyTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNinetyTeams,
                    request_deserializer=scraper_dot_core_dot_scraper__pb2.ScraperRequest.FromString,
                    response_serializer=scraper_dot_core_dot_scraper__pb2.ScraperResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scraper.ScraperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scraper.ScraperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScraperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNinetyZPNs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetNinetyZPNs',
            scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
            scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNinetyLeagues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetNinetyLeagues',
            scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
            scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNinetyLeagueStandings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetNinetyLeagueStandings',
            scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
            scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNinetyFixtures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetNinetyFixtures',
            scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
            scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNinetyTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetNinetyTeams',
            scraper_dot_core_dot_scraper__pb2.ScraperRequest.SerializeToString,
            scraper_dot_core_dot_scraper__pb2.ScraperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
