# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scraper/core/scraper.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scraper/core/scraper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ascraper/core/scraper.proto\x12\x07scraper\"\x1d\n\x0eScraperRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1f\n\x0fScraperResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xb2\x02\n\x0eScraperService\x12\x42\n\rGetNinetyZPNs\x12\x17.scraper.ScraperRequest\x1a\x18.scraper.ScraperResponse\x12\x45\n\x10GetNinetyLeagues\x12\x17.scraper.ScraperRequest\x1a\x18.scraper.ScraperResponse\x12M\n\x18GetNinetyLeagueStandings\x12\x17.scraper.ScraperRequest\x1a\x18.scraper.ScraperResponse\x12\x46\n\x11GetNinetyFixtures\x12\x17.scraper.ScraperRequest\x1a\x18.scraper.ScraperResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scraper.core.scraper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRAPERREQUEST']._serialized_start=39
  _globals['_SCRAPERREQUEST']._serialized_end=68
  _globals['_SCRAPERRESPONSE']._serialized_start=70
  _globals['_SCRAPERRESPONSE']._serialized_end=101
  _globals['_SCRAPERSERVICE']._serialized_start=104
  _globals['_SCRAPERSERVICE']._serialized_end=410
# @@protoc_insertion_point(module_scope)
